name: CICD Workflow


on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  cicd:
    name: linter-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run linter
        run: uv run ruff check && uv run ruff format

      - name: Run tests
        run: uv run pytest 
